name: Create PR to master

on:
  push:
    tags:
      - "v*"

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        uses: cli/cli@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request to master
        run: gh pr create --base master --head development --title "Release PR" --body "Automated PR to merge development into master"
